typical_male:
  - male_hand
  - animal:
      - dog
      - horse
      - pig
  - toned_male
  - goblin
  - fat_man
  - old_man
  - muscular_male
  - dark_skin_male:
      - brown
      - gray
      - black

untypical_male:
  - untypical_male_hand
  - shota
  - otokonoko

female_only:
  - female_hand
  - futanari

ambiguous:
# 这里的ambiguous意味着图像本身就不明确，而不意味着这张图对于模型难以识别。
  - ambiguous_hand
  - unfocused_shadow
  - ambiguous_shota_or_toned_male
